version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: product_insight_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_insight
    ports:
      - '6543:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d product_insight']
      interval: 5s
      timeout: 3s
      retries: 5
