import { spawn } from 'node:child_process';

export type TranscriptTimelineLine = {
  timestamp: string;
  seconds: number;
  start: number;
  startMs: number;
  text: string;
};

export type YtDlpTranscriptSuccess = {
  ok: true;
  source: 'yt-dlp';
  videoId: string;
  languageCode: string;
  languageName: string;
  lineCount: number;
  timeline: TranscriptTimelineLine[];
  transcript: string;
  isAutoGenerated: boolean;
  title: string;
};

export class YtDlpTranscriptError extends Error {
  code: string;
  status: number;

  constructor(code: string, message?: string, status = 500) {
    super(message || code);
    this.name = 'YtDlpTranscriptError';
    this.code = code;
    this.status = status;
  }
}

type YtDlpSubtitleEntry = {
  ext?: string;
  url?: string;
  name?: string;
};

type YtDlpVideoInfo = {
  id?: string;
  title?: string;
  subtitles?: Record<string, YtDlpSubtitleEntry[]>;
  automatic_captions?: Record<string, YtDlpSubtitleEntry[]>;
};

type CandidateTrack = {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  ext: string;
  url: string;
};

type YtDlpRunResult = {
  code: number | null;
  stdout: string;
  stderr: string;
  timedOut: boolean;
  usedCookies: boolean;
  usedCookieHeader: boolean;
  cookieBrowser: string;
  mode: YtDlpRunMode;
  elapsedMs: number;
  stdoutBytes: number;
  stderrBytes: number;
};

type YtDlpRunMode = 'tracks_print' | 'full_json';

const DEFAULT_COOKIES_BROWSER = 'chrome';
const MAX_COOKIE_HEADER_BYTES = 7000;
const FAST_PROBE_TIMEOUT_MIN_MS = 3000;
const FAST_PROBE_TIMEOUT_MAX_MS = 6500;

function parseLanguages(input: string[] | string | undefined): string[] {
  if (!input) return [];
  const raw = Array.isArray(input) ? input.join(',') : input;
  const seen = new Set<string>();
  return raw
    .split(',')
    .map((token) => token.trim())
    .filter(Boolean)
    .filter((token) => {
      const key = token.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, 8);
}

function buildYtDlpEnv(): NodeJS.ProcessEnv {
  if (process.env.YT_DLP_KEEP_PROXY === '1') {
    return { ...process.env };
  }
  const env = { ...process.env };
  delete env.HTTP_PROXY;
  delete env.HTTPS_PROXY;
  delete env.NO_PROXY;
  delete env.ALL_PROXY;
  delete env.http_proxy;
  delete env.https_proxy;
  delete env.no_proxy;
  delete env.all_proxy;
  return env;
}

function normalizeCookieBrowser(raw: string): string {
  const value = String(raw || '').trim();
  return value || '';
}

function resolveCookieBrowser(): string {
  const explicit = normalizeCookieBrowser(
    String(process.env.YT_DLP_COOKIES_FROM_BROWSER || '')
  );
  if (explicit) {
    return explicit;
  }
  return DEFAULT_COOKIES_BROWSER;
}

function shouldRetryWithCookies(): boolean {
  const raw = String(process.env.YT_DLP_COOKIE_RETRY || '1')
    .trim()
    .toLowerCase();
  if (!raw) return true;
  if (raw === '0' || raw === 'off' || raw === 'false' || raw === 'no') return false;
  return true;
}

function shouldUseBrowserCookieStoreFallback(): boolean {
  const raw = String(process.env.YT_DLP_BROWSER_COOKIE_FALLBACK || '0')
    .trim()
    .toLowerCase();
  if (!raw) return false;
  if (raw === '1' || raw === 'on' || raw === 'true' || raw === 'yes') return true;
  return false;
}

function normalizeCookieSource(raw: string): string {
  return String(raw || '')
    .replace(/[\r\n]/g, ' ')
    .trim()
    .toLowerCase();
}

function isExplicitBrowserCookieFallbackSource(cookieSource: string): boolean {
  if (!cookieSource) return false;
  return (
    cookieSource === 'browser_cookie_opt_in' ||
    cookieSource === 'explicit_browser_cookie_opt_in'
  );
}

function resolveFastProbeTimeoutMs(timeoutMs: number): number {
  const bounded = Math.max(
    FAST_PROBE_TIMEOUT_MIN_MS,
    Math.min(FAST_PROBE_TIMEOUT_MAX_MS, Math.floor(timeoutMs * 0.72))
  );
  return Math.min(timeoutMs, bounded);
}

function sanitizeCookieHeader(raw: string): string {
  const text = String(raw || '')
    .replace(/[\r\n]/g, '')
    .trim();
  if (!text) return '';
  const out: string[] = [];
  const seen = new Set<string>();
  for (const token of text.split(';')) {
    const pair = String(token || '').trim();
    if (!pair) continue;
    const equalIndex = pair.indexOf('=');
    if (equalIndex <= 0) continue;
    const name = pair.slice(0, equalIndex).trim();
    const value = pair.slice(equalIndex + 1).trim();
    if (!name || !value) continue;
    if (!/^[A-Za-z0-9!#$%&'*+\-.^_`|~]+$/.test(name)) continue;
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    const safeValue = value.replace(/;/g, '');
    out.push(`${name}=${safeValue}`);
    if (out.join('; ').length >= MAX_COOKIE_HEADER_BYTES) {
      break;
    }
  }
  let header = out.join('; ');
  if (header.length > MAX_COOKIE_HEADER_BYTES) {
    header = header.slice(0, MAX_COOKIE_HEADER_BYTES);
  }
  return header;
}

function normalizeText(value: unknown): string {
  return String(value || '')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function decodeEntities(text: string): string {
  return String(text || '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ');
}

function stripTags(text: string): string {
  return String(text || '').replace(/<[^>]+>/g, '');
}

function formatClock(secondsInput: number): string {
  const safe = Math.max(0, Math.floor(secondsInput));
  const hours = Math.floor(safe / 3600);
  const minutes = Math.floor((safe % 3600) / 60);
  const seconds = safe % 60;
  if (hours > 0) {
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(
      2,
      '0'
    )}:${String(seconds).padStart(2, '0')}`;
  }
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

function pushTimelineLine(
  timeline: TranscriptTimelineLine[],
  secondsInput: number,
  rawText: unknown
): void {
  if (!Number.isFinite(secondsInput)) return;
  const seconds = Math.max(0, Number(secondsInput));
  const text = normalizeText(decodeEntities(stripTags(String(rawText || ''))));
  if (!text) return;
  const timestamp = formatClock(seconds);
  const start = Math.round(seconds * 1000) / 1000;
  const startMs = Math.round(seconds * 1000);
  const previous = timeline[timeline.length - 1];
  if (previous && previous.startMs === startMs && previous.text === text) return;
  timeline.push({
    timestamp,
    seconds: start,
    start,
    startMs,
    text
  });
}

function parseXmlStartValue(raw: string, millisecondHint: boolean): number {
  const value = String(raw || '').trim().toLowerCase();
  if (!value) return Number.NaN;
  if (value.includes(':')) {
    return parseTimestampToSeconds(value.replace(',', '.'));
  }
  if (value.endsWith('ms')) {
    const ms = Number.parseFloat(value.slice(0, -2));
    return Number.isFinite(ms) ? ms / 1000 : Number.NaN;
  }
  if (value.endsWith('s')) {
    const seconds = Number.parseFloat(value.slice(0, -1));
    return Number.isFinite(seconds) ? seconds : Number.NaN;
  }
  const num = Number.parseFloat(value);
  if (!Number.isFinite(num)) return Number.NaN;
  return millisecondHint ? num / 1000 : num;
}

function parseTimestampToSeconds(raw: string): number {
  const text = String(raw || '').trim();
  if (!text) return Number.NaN;
  const parts = text.split(':').map((item) => item.trim());
  if (parts.length < 2 || parts.length > 3) return Number.NaN;
  const [head, mid, tail] = parts.length === 3 ? parts : ['0', parts[0], parts[1]];
  const hours = Number.parseFloat(head);
  const minutes = Number.parseFloat(mid);
  const seconds = Number.parseFloat(tail);
  if (!Number.isFinite(hours) || !Number.isFinite(minutes) || !Number.isFinite(seconds)) {
    return Number.NaN;
  }
  return Math.max(0, hours * 3600 + minutes * 60 + seconds);
}

function parseJson3Timeline(payload: string): TranscriptTimelineLine[] {
  const text = String(payload || '').trim();
  if (!text.startsWith('{') && !text.startsWith('[')) return [];
  let parsed: any = null;
  try {
    parsed = JSON.parse(text);
  } catch {
    return [];
  }

  const events = Array.isArray(parsed?.events) ? parsed.events : [];
  const timeline: TranscriptTimelineLine[] = [];
  for (const event of events) {
    const tStartMs = Number(event?.tStartMs);
    if (!Number.isFinite(tStartMs)) continue;
    const segments = Array.isArray(event?.segs) ? event.segs : [];
    const merged = segments
      .map((segment: any) => String(segment?.utf8 || ''))
      .join('')
      .replace(/\u200b/g, '');
    pushTimelineLine(timeline, tStartMs / 1000, merged);
  }
  return timeline;
}

function parseVttTimeline(payload: string): TranscriptTimelineLine[] {
  const lines = String(payload || '').split(/\r?\n/);
  const timeline: TranscriptTimelineLine[] = [];
  let index = 0;
  while (index < lines.length) {
    const line = lines[index].trim();
    if (!line.includes('-->')) {
      index += 1;
      continue;
    }
    const cueMatch = line.match(
      /((?:\d{1,2}:)?\d{2}:\d{2}(?:[.,]\d{1,3})?)\s*-->/
    );
    if (!cueMatch) {
      index += 1;
      continue;
    }
    const seconds = parseTimestampToSeconds(cueMatch[1].replace(',', '.'));
    index += 1;
    const textLines: string[] = [];
    while (index < lines.length && lines[index].trim()) {
      textLines.push(lines[index]);
      index += 1;
    }
    pushTimelineLine(timeline, seconds, textLines.join(' '));
    index += 1;
  }
  return timeline;
}

function readXmlAttr(attrs: string, key: string): string {
  const regex = new RegExp(`${key}\\s*=\\s*(['"])(.*?)\\1`, 'i');
  const match = regex.exec(String(attrs || ''));
  return match ? String(match[2] || '') : '';
}

function parseXmlTimeline(payload: string): TranscriptTimelineLine[] {
  const text = String(payload || '').trim();
  if (!text.startsWith('<')) return [];
  const timeline: TranscriptTimelineLine[] = [];
  const regex = /<(text|p)\b([^>]*)>([\s\S]*?)<\/\1>/gi;
  let match: RegExpExecArray | null = null;
  while ((match = regex.exec(text)) !== null) {
    const attrs = String(match[2] || '');
    const body = String(match[3] || '');
    const start =
      readXmlAttr(attrs, 'start') ||
      readXmlAttr(attrs, 'begin') ||
      readXmlAttr(attrs, 't');
    if (!start) continue;
    const hasMsHint = Boolean(readXmlAttr(attrs, 't'));
    const seconds = parseXmlStartValue(start, hasMsHint);
    pushTimelineLine(timeline, seconds, body);
  }
  return timeline;
}

function parseTimelinePayload(payload: string, ext: string): TranscriptTimelineLine[] {
  const normalizedExt = String(ext || '').trim().toLowerCase();
  if (normalizedExt === 'json3') {
    return parseJson3Timeline(payload);
  }
  if (normalizedExt === 'vtt' || normalizedExt === 'webvtt') {
    return parseVttTimeline(payload);
  }
  if (normalizedExt === 'ttml' || normalizedExt === 'srv3' || normalizedExt === 'xml') {
    return parseXmlTimeline(payload);
  }
  const fromJson3 = parseJson3Timeline(payload);
  if (fromJson3.length > 0) return fromJson3;
  const fromXml = parseXmlTimeline(payload);
  if (fromXml.length > 0) return fromXml;
  return parseVttTimeline(payload);
}

function formatRank(ext: string): number {
  const value = String(ext || '').toLowerCase();
  if (value === 'json3') return 0;
  if (value === 'srv3') return 1;
  if (value === 'ttml' || value === 'xml') return 2;
  if (value === 'vtt' || value === 'webvtt') return 3;
  return 99;
}

function buildLanguagePriority(requested: string[], candidates: CandidateTrack[]): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const push = (value: string) => {
    const code = String(value || '').trim();
    if (!code) return;
    const key = code.toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    out.push(code);
  };

  requested.forEach(push);
  candidates.forEach((item) => push(item.languageCode));
  return out;
}

function languageRank(languageCode: string, priority: string[]): number {
  const code = String(languageCode || '').trim().toLowerCase();
  if (!code) return 9999;
  for (let index = 0; index < priority.length; index += 1) {
    const target = String(priority[index] || '').trim().toLowerCase();
    if (!target) continue;
    if (code === target) return index;
  }
  for (let index = 0; index < priority.length; index += 1) {
    const target = String(priority[index] || '').trim().toLowerCase();
    if (!target) continue;
    if (code.startsWith(target) || target.startsWith(code)) return 100 + index;
  }
  return 9999;
}

function normalizeVideoInfo(raw: unknown): YtDlpVideoInfo | null {
  if (!raw || typeof raw !== 'object') return null;
  const payload = raw as Record<string, unknown>;
  return {
    id: String(payload.id || '').trim(),
    title: String(payload.title || '').trim(),
    subtitles:
      payload.subtitles && typeof payload.subtitles === 'object'
        ? (payload.subtitles as Record<string, YtDlpSubtitleEntry[]>)
        : {},
    automatic_captions:
      payload.automatic_captions && typeof payload.automatic_captions === 'object'
        ? (payload.automatic_captions as Record<string, YtDlpSubtitleEntry[]>)
        : {}
  };
}

function collectCandidates(info: YtDlpVideoInfo): CandidateTrack[] {
  const out: CandidateTrack[] = [];
  const seen = new Set<string>();
  const pushFromMap = (
    map: Record<string, YtDlpSubtitleEntry[]> | undefined,
    isAutoGenerated: boolean
  ) => {
    if (!map || typeof map !== 'object') return;
    for (const [languageCodeRaw, entriesRaw] of Object.entries(map)) {
      const languageCode = String(languageCodeRaw || '').trim();
      if (!languageCode) continue;
      const entries = Array.isArray(entriesRaw) ? entriesRaw : [];
      for (const entry of entries) {
        const ext = String(entry?.ext || '').trim().toLowerCase();
        const url = String(entry?.url || '').trim();
        if (!ext || !url) continue;
        const key = `${languageCode.toLowerCase()}|${ext}|${url}`;
        if (seen.has(key)) continue;
        seen.add(key);
        out.push({
          languageCode,
          languageName: String(entry?.name || languageCode).trim(),
          isAutoGenerated,
          ext,
          url
        });
      }
    }
  };

  pushFromMap(info.subtitles, false);
  pushFromMap(info.automatic_captions, true);
  return out;
}

function parseJsonFromStdout(stdout: string): Record<string, unknown> | null {
  const text = String(stdout || '').trim();
  if (!text) return null;
  const firstCurly = text.indexOf('{');
  if (firstCurly === -1) return null;
  const possible = text.slice(firstCurly).trim();
  try {
    const parsed = JSON.parse(possible);
    if (parsed && typeof parsed === 'object') {
      return parsed as Record<string, unknown>;
    }
  } catch {
    return null;
  }
  return null;
}

function inferYtDlpError(stderr: string): { code: string; status: number } {
  const text = String(stderr || '').toLowerCase();
  if (
    text.includes('unable to connect to proxy') ||
    text.includes('proxyerror') ||
    text.includes('proxy connection failed')
  ) {
    return { code: 'proxy_failed', status: 502 };
  }
  if (text.includes('sign in to confirm') || text.includes('login required')) {
    return { code: 'login_required', status: 502 };
  }
  if (
    text.includes('too many requests') ||
    text.includes('http error 429') ||
    text.includes('captcha') ||
    text.includes('request blocked') ||
    text.includes('forbidden')
  ) {
    return { code: 'request_blocked', status: 502 };
  }
  if (
    text.includes('video unavailable') ||
    text.includes('private video') ||
    text.includes('this video is unavailable') ||
    text.includes('not available')
  ) {
    return { code: 'video_unavailable', status: 404 };
  }
  if (text.includes('age restricted') || text.includes('age-restricted')) {
    return { code: 'age_restricted', status: 404 };
  }
  return { code: 'yt_dlp_failed', status: 500 };
}

function parseTrackMapLine(line: string): Record<string, YtDlpSubtitleEntry[]> {
  const raw = String(line || '').trim();
  if (!raw || raw === 'NA' || raw === 'null') return {};
  try {
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return {};
    }
    return parsed as Record<string, YtDlpSubtitleEntry[]>;
  } catch {
    return {};
  }
}

function parseTrackMapsFromStdout(
  stdout: string,
  videoId: string
): YtDlpVideoInfo | null {
  const lines = String(stdout || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
  if (!lines.length) return null;
  const automaticCaptions = parseTrackMapLine(lines[0] || '');
  const subtitles = parseTrackMapLine(lines[1] || '');
  return {
    id: videoId,
    title: '',
    subtitles,
    automatic_captions: automaticCaptions
  };
}

function toTimeoutError(result: YtDlpRunResult): YtDlpTranscriptError {
  const hasOutput =
    String(result.stdout || '').trim().length > 0 ||
    String(result.stderr || '').trim().length > 0;
  const code = hasOutput
    ? 'bridge_timeout_after_output'
    : 'bridge_timeout_no_output';
  const detail = hasOutput
    ? `yt-dlp timed out after partial output (mode=${result.mode}, elapsedMs=${result.elapsedMs})`
    : `yt-dlp timed out with no output (mode=${result.mode}, elapsedMs=${result.elapsedMs})`;
  return new YtDlpTranscriptError(code, detail, 504);
}

function buildYtDlpArgs(
  videoId: string,
  options: {
    mode: YtDlpRunMode;
    cookieBrowser?: string;
    cookieHeader?: string;
  } = {}
): string[] {
  const mode = options.mode === 'tracks_print' ? 'tracks_print' : 'full_json';
  const cookieBrowser = String(options.cookieBrowser || '').trim();
  const cookieHeader = sanitizeCookieHeader(String(options.cookieHeader || ''));
  const args = [
    '--skip-download',
    '--no-warnings',
    '--no-playlist'
  ];
  if (mode === 'tracks_print' && !cookieBrowser) {
    args.push('--extractor-args', 'youtube:player_client=android');
    args.push('--print', '%(automatic_captions)j');
    args.push('--print', '%(subtitles)j');
  } else {
    args.push('--dump-single-json');
  }
  if (cookieHeader) {
    args.push('--add-header', `Cookie: ${cookieHeader}`);
  }
  if (cookieBrowser) {
    args.push('--cookies-from-browser', cookieBrowser);
  }
  args.push('--', `https://www.youtube.com/watch?v=${videoId}`);
  return args;
}

async function runYtDlp(
  videoId: string,
  timeoutMs: number,
  options: {
    mode: YtDlpRunMode;
    cookieBrowser?: string;
    cookieHeader?: string;
  } = {}
): Promise<YtDlpRunResult> {
  const mode = options.mode === 'tracks_print' ? 'tracks_print' : 'full_json';
  const ytDlpBin = process.env.YT_DLP_BIN || 'yt-dlp';
  const cookieBrowser = String(options.cookieBrowser || '').trim();
  const cookieHeader = sanitizeCookieHeader(String(options.cookieHeader || ''));
  const args = buildYtDlpArgs(videoId, {
    mode,
    cookieBrowser,
    cookieHeader
  });

  return new Promise((resolve, reject) => {
    const startedAt = Date.now();
    const child = spawn(ytDlpBin, args, {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: buildYtDlpEnv()
    });

    let stdout = '';
    let stderr = '';
    let timedOut = false;

    const timer = setTimeout(() => {
      timedOut = true;
      child.kill('SIGKILL');
    }, timeoutMs);

    child.stdout.on('data', (chunk: Buffer) => {
      stdout += chunk.toString('utf8');
    });

    child.stderr.on('data', (chunk: Buffer) => {
      stderr += chunk.toString('utf8');
    });

    child.on('error', (error) => {
      clearTimeout(timer);
      reject(error);
    });

    child.on('close', (code) => {
      clearTimeout(timer);
      const elapsedMs = Math.max(0, Date.now() - startedAt);
      resolve({
        code,
        stdout,
        stderr,
        timedOut,
        usedCookies: Boolean(cookieBrowser),
        usedCookieHeader: Boolean(cookieHeader),
        cookieBrowser: String(cookieBrowser || ''),
        mode,
        elapsedMs,
        stdoutBytes: Buffer.byteLength(stdout, 'utf8'),
        stderrBytes: Buffer.byteLength(stderr, 'utf8')
      });
    });
  });
}

async function fetchTextWithTimeout(url: string, timeoutMs: number): Promise<{
  ok: boolean;
  status: number;
  text: string;
}> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, {
      method: 'GET',
      cache: 'no-store',
      signal: controller.signal
    });
    const text = await response.text();
    return {
      ok: response.ok,
      status: response.status,
      text
    };
  } finally {
    clearTimeout(timer);
  }
}

export async function fetchTranscriptViaYtDlp(params: {
  videoId: string;
  languages?: string[] | string;
  timeoutMs?: number;
  cookieHeader?: string;
  cookieSource?: string;
}): Promise<YtDlpTranscriptSuccess> {
  const videoId = String(params.videoId || '').trim();
  if (!videoId) {
    throw new YtDlpTranscriptError('missing_video_id', 'videoId is required', 400);
  }
  const timeoutMs = Number.isFinite(params.timeoutMs)
    ? Math.max(3000, Number(params.timeoutMs))
    : 25000;
  const requestedLanguages = parseLanguages(params.languages);
  const cookieRetryEnabled = shouldRetryWithCookies();
  const browserCookieFallbackEnabled = shouldUseBrowserCookieStoreFallback();
  const cookieBrowser = resolveCookieBrowser();
  const incomingCookieHeader = sanitizeCookieHeader(String(params.cookieHeader || ''));
  const incomingCookieSource = normalizeCookieSource(String(params.cookieSource || ''));
  const browserCookieFallbackAllowed =
    cookieRetryEnabled &&
    browserCookieFallbackEnabled &&
    isExplicitBrowserCookieFallbackSource(incomingCookieSource);

  const runAttempt = async (
    mode: YtDlpRunMode,
    runTimeoutMs: number,
    options: { cookieHeader?: string; cookieBrowser?: string } = {}
  ): Promise<YtDlpRunResult> => {
    try {
      return await runYtDlp(videoId, runTimeoutMs, {
        mode,
        cookieHeader: options.cookieHeader,
        cookieBrowser: options.cookieBrowser
      });
    } catch (error: any) {
      const code = String(error?.code || '');
      if (code === 'ENOENT') {
        throw new YtDlpTranscriptError(
          'yt_dlp_not_installed',
          'yt-dlp is not installed',
          503
        );
      }
      throw new YtDlpTranscriptError(
        'yt_dlp_failed',
        String(error?.message || error || 'yt-dlp failed'),
        500
      );
    }
  };

  let result = await runAttempt('tracks_print', resolveFastProbeTimeoutMs(timeoutMs), {
    cookieHeader: incomingCookieHeader
  });
  if (result.timedOut) {
    throw toTimeoutError(result);
  }

  let info: YtDlpVideoInfo | null = null;
  if (result.code === 0) {
    info = parseTrackMapsFromStdout(result.stdout, videoId);
  } else {
    const firstError = inferYtDlpError(result.stderr);
    const canRetryWithBrowserCookieStore =
      !incomingCookieHeader &&
      firstError.code === 'login_required' &&
      browserCookieFallbackAllowed &&
      Boolean(cookieBrowser);
    if (canRetryWithBrowserCookieStore) {
      const cookieResult = await runAttempt('full_json', Math.max(timeoutMs, 9000), {
        cookieBrowser
      });
      if (cookieResult.timedOut) {
        throw toTimeoutError(cookieResult);
      }
      if (cookieResult.code !== 0) {
        const cookieError = inferYtDlpError(cookieResult.stderr);
        throw new YtDlpTranscriptError(
          cookieError.code,
          String(cookieResult.stderr || cookieError.code).trim() || cookieError.code,
          cookieError.status
        );
      }
      result = cookieResult;
      info = normalizeVideoInfo(parseJsonFromStdout(result.stdout));
    } else {
      throw new YtDlpTranscriptError(
        firstError.code,
        String(result.stderr || firstError.code).trim() || firstError.code,
        firstError.status
      );
    }
  }

  let candidates = info ? collectCandidates(info) : [];
  if (!candidates.length) {
    const fallbackTimeoutMs = Math.max(3000, Math.min(timeoutMs, timeoutMs - result.elapsedMs));
    const fallbackResult = await runAttempt('full_json', fallbackTimeoutMs, {
      cookieHeader: incomingCookieHeader
    });
    if (fallbackResult.timedOut) {
      throw toTimeoutError(fallbackResult);
    }
    if (fallbackResult.code !== 0) {
      const fallbackError = inferYtDlpError(fallbackResult.stderr);
      throw new YtDlpTranscriptError(
        fallbackError.code,
        String(fallbackResult.stderr || fallbackError.code).trim() || fallbackError.code,
        fallbackError.status
      );
    }
    result = fallbackResult;
    info = normalizeVideoInfo(parseJsonFromStdout(result.stdout));
    if (!info) {
      throw new YtDlpTranscriptError('yt_dlp_parse_failed', 'invalid yt-dlp payload', 500);
    }
    candidates = collectCandidates(info);
  }

  if (!candidates.length) {
    throw new YtDlpTranscriptError('no_caption_tracks', 'no subtitle tracks from yt-dlp', 404);
  }
  if (!info) {
    throw new YtDlpTranscriptError('yt_dlp_parse_failed', 'invalid yt-dlp payload', 500);
  }

  const languagePriority = buildLanguagePriority(requestedLanguages, candidates);
  candidates.sort((a, b) => {
    const languageDiff =
      languageRank(a.languageCode, languagePriority) -
      languageRank(b.languageCode, languagePriority);
    if (languageDiff !== 0) return languageDiff;
    if (a.isAutoGenerated !== b.isAutoGenerated) {
      return a.isAutoGenerated ? 1 : -1;
    }
    const formatDiff = formatRank(a.ext) - formatRank(b.ext);
    if (formatDiff !== 0) return formatDiff;
    return a.languageCode.localeCompare(b.languageCode);
  });

  const fetchTimeoutMs = Math.max(1600, Math.min(5000, Math.floor(timeoutMs * 0.45)));
  for (const candidate of candidates) {
    let response: { ok: boolean; status: number; text: string };
    try {
      response = await fetchTextWithTimeout(candidate.url, fetchTimeoutMs);
    } catch (error: any) {
      const message = String(error?.message || '');
      if (message.toLowerCase().includes('abort')) {
        continue;
      }
      continue;
    }
    if (!response.ok || !response.text) continue;
    const timeline = parseTimelinePayload(response.text, candidate.ext);
    if (!timeline.length) continue;
    const transcript = timeline.map((line) => line.text).join(' ').trim();
    return {
      ok: true,
      source: 'yt-dlp',
      videoId: String(info.id || videoId).trim() || videoId,
      languageCode: candidate.languageCode || '',
      languageName: candidate.languageName || '',
      lineCount: timeline.length,
      timeline,
      transcript,
      isAutoGenerated: Boolean(candidate.isAutoGenerated),
      title: String(info.title || '').trim()
    };
  }

  throw new YtDlpTranscriptError('captions_not_found', 'yt-dlp subtitle payload is empty', 404);
}
