const DEBUG = true;

function debugLog(...args) {
  if (!DEBUG) return;
  console.log("[yt-analyzer]", ...args);
}

const PLAYER_RESPONSE_WAIT_MS = 1200;
const PLAYER_RESPONSE_POLL_MS = 150;

function isElementVisible(element) {
  if (!element) return false;
  const style = window.getComputedStyle(element);
  if (style.display === "none" || style.visibility === "hidden") return false;
  const rect = element.getBoundingClientRect();
  if (rect.width === 0 || rect.height === 0) return false;
  return true;
}

function readPlayerResponse(expectedVideoId) {
  const fromPlayer = readPlayerResponseFromPlayer();
  const fromWindow = readPlayerResponseFromWindow();
  const fromDom = readPlayerResponseFromDom();
  if (expectedVideoId) {
    if (fromPlayer?.videoDetails?.videoId === expectedVideoId) return fromPlayer;
    if (fromWindow?.videoDetails?.videoId === expectedVideoId) return fromWindow;
    if (fromDom?.videoDetails?.videoId === expectedVideoId) return fromDom;
  }
  return fromPlayer || fromWindow || fromDom || null;
}

function readPlayerResponseFromPlayer() {
  try {
    const player = document.getElementById("movie_player");
    if (!player) return null;
    if (typeof player.getPlayerResponse === "function") {
      const response = player.getPlayerResponse();
      if (response && typeof response === "object") return response;
    }
  } catch {
    return null;
  }
  return null;
}

function readPlayerResponseFromWindow() {
  if (window.ytInitialPlayerResponse) {
    return window.ytInitialPlayerResponse;
  }
  const rawResponse = window.ytplayer?.config?.args?.player_response;
  if (rawResponse) {
    if (typeof rawResponse === "string") {
      try {
        return JSON.parse(rawResponse);
      } catch {
        return null;
      }
    }
    return rawResponse;
  }
  return null;
}

function readPlayerResponseFromDom() {
  const scripts = Array.from(document.scripts || []);
  const candidates = scripts
    .map((script) => script.textContent || "")
    .filter(Boolean);
  const preferred = candidates.find(
    (text) =>
      text.includes("ytInitialPlayerResponse") &&
      text.includes("captionTracks")
  );
  const fallback = candidates.find((text) =>
    text.includes("ytInitialPlayerResponse")
  );
  const scriptText = preferred || fallback;
  if (!scriptText) return null;
  const jsonText = extractJsonAfterMarker(
    scriptText,
    "ytInitialPlayerResponse"
  );
  if (!jsonText) return null;
  try {
    return JSON.parse(jsonText);
  } catch {
    return null;
  }
}

function extractJsonAfterMarker(text, marker) {
  const markerIndex = text.indexOf(marker);
  if (markerIndex === -1) return null;
  const start = text.indexOf("{", markerIndex);
  if (start === -1) return null;
  let depth = 0;
  for (let i = start; i < text.length; i += 1) {
    const char = text[i];
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) {
      return text.slice(start, i + 1);
    }
  }
  return null;
}

function readVideoDetails(response) {
  return {
    videoId: response?.videoDetails?.videoId ?? "",
    title: response?.videoDetails?.title ?? document.title ?? "",
    url: window.location.href,
  };
}

function readCaptionTracks(response) {
  return (
    response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
  );
}

function formatTrackName(track) {
  if (track?.name?.simpleText) return track.name.simpleText;
  if (Array.isArray(track?.name?.runs)) {
    return track.name.runs.map((run) => run.text).join("");
  }
  return track?.languageCode ?? "unknown";
}

function pickBestTrack(tracks, preferredLanguage) {
  if (!tracks || tracks.length === 0) return null;
  const preferred = (preferredLanguage ?? "").toLowerCase();
  const matches = preferred
    ? tracks.filter((track) =>
        (track.languageCode ?? "").toLowerCase().startsWith(preferred)
      )
    : [];
  const pickManual = (list) =>
    list.find((track) => track.kind !== "asr") ?? list[0];
  if (matches.length > 0) return pickManual(matches);
  const manual = tracks.find((track) => track.kind !== "asr");
  return manual ?? tracks[0];
}

function buildTrackInfo(track) {
  return {
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    name: formatTrackName(track),
    kind: track.kind ?? "",
    isAutoGenerated: track.kind === "asr",
  };
}


async function handleGetCaptions(preferredLanguage) {
  const expectedVideoId = extractVideoIdFromLocation(window.location.href);
  let response = readPlayerResponse(expectedVideoId);
  if (
    expectedVideoId &&
    (!response?.videoDetails?.videoId ||
      response.videoDetails.videoId !== expectedVideoId)
  ) {
    response = await waitForPlayerResponse(
      expectedVideoId,
      PLAYER_RESPONSE_WAIT_MS,
      PLAYER_RESPONSE_POLL_MS
    );
  }
  if (!response) {
    return { ok: false, error: "player_response_not_found" };
  }
  if (
    expectedVideoId &&
    response?.videoDetails?.videoId &&
    response.videoDetails.videoId !== expectedVideoId
  ) {
    return {
      ok: false,
      error: "player_response_mismatch",
      expectedVideoId,
      actualVideoId: response.videoDetails.videoId,
    };
  }
  const video = readVideoDetails(response);
  const tracks = readCaptionTracks(response);
  if (!tracks || tracks.length === 0) {
    return { ok: false, error: "no_caption_tracks" };
  }
  const selected = pickBestTrack(tracks, preferredLanguage);
  if (!selected?.baseUrl) {
    return { ok: false, error: "caption_track_missing_url" };
  }
  return {
    ok: true,
    data: {
      video,
      track: buildTrackInfo(selected),
      trackCount: tracks.length,
    },
  };
}

function extractVideoIdFromLocation(url) {
  try {
    const parsed = new URL(url);
    if (parsed.hostname.includes("youtu.be")) {
      return parsed.pathname.replace("/", "");
    }
    if (parsed.hostname.includes("youtube.com")) {
      const v = parsed.searchParams.get("v");
      if (v) return v;
      const parts = parsed.pathname.split("/").filter(Boolean);
      const shortsIndex = parts.indexOf("shorts");
      if (shortsIndex !== -1 && parts[shortsIndex + 1]) {
        return parts[shortsIndex + 1];
      }
      const embedIndex = parts.indexOf("embed");
      if (embedIndex !== -1 && parts[embedIndex + 1]) {
        return parts[embedIndex + 1];
      }
      const liveIndex = parts.indexOf("live");
      if (liveIndex !== -1 && parts[liveIndex + 1]) {
        return parts[liveIndex + 1];
      }
      return "";
    }
  } catch {
    return "";
  }
  return "";
}

async function waitForPlayerResponse(expectedVideoId, timeoutMs, intervalMs) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const candidate = readPlayerResponse(expectedVideoId);
    if (
      candidate?.videoDetails?.videoId &&
      candidate.videoDetails.videoId === expectedVideoId
    ) {
      return candidate;
    }
    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
  return readPlayerResponse(expectedVideoId) || readPlayerResponse();
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message?.type === "GET_CAPTIONS") {
    const preferredLanguage =
      typeof message.preferredLanguage === "string"
        ? message.preferredLanguage
        : "en";
    handleGetCaptions(preferredLanguage)
      .then((result) => sendResponse(result))
      .catch((error) =>
        sendResponse({ ok: false, error: error?.message || "unknown_error" })
      );
    return true;
  }
  if (message?.type === "GET_TRANSCRIPT_DOM") {
    handleGetTranscriptDom()
      .then((result) => sendResponse(result))
      .catch((error) =>
        sendResponse({ ok: false, error: error?.message || "unknown_error" })
      );
    return true;
  }
});



async function handleGetTranscriptDom() {
  const existing = await readTranscriptFromDom();
  if (existing) {
    return { ok: true, data: { transcript: existing } };
  }
  const openResult = await openTranscriptPanel();
  if (!openResult.ok) {
    return {
      ok: false,
      error: "transcript_panel_not_found",
      debug: openResult.debug,
    };
  }
  const transcript = await readTranscriptFromDom();
  if (!transcript) {
    return { ok: false, error: "transcript_empty", debug: openResult.debug };
  }
  return { ok: true, data: { transcript } };
}

async function openTranscriptPanel() {
  const debug = {
    alreadyOpen: false,
    expanded: false,
    directButtonFound: false,
    menuButtonFound: false,
    menuPopupFound: false,
    menuItemFound: false,
    openedAfterDirect: false,
    openedAfterMenu: false,
    menuButtonDesc: null,
    menuItemLabels: [],
  };
  if (isTranscriptPanelOpen()) {
    debugLog("transcript panel already open");
    debug.alreadyOpen = true;
    return { ok: true, debug };
  }
  debug.expanded = await expandDescriptionIfNeeded();
  if (isTranscriptPanelOpen()) {
    debugLog("transcript panel opened after expand");
    return { ok: true, debug };
  }
  const openedDirect = await openTranscriptPanelFromDirectButton();
  debug.directButtonFound = openedDirect;
  if (openedDirect) {
    const ready = await waitForTranscriptPanel(3500);
    debug.openedAfterDirect = ready;
    if (ready) return { ok: true, debug };
  }
  const menuResult = await openTranscriptPanelFromMenu();
  debug.menuButtonFound = menuResult.menuButtonFound;
  debug.menuPopupFound = menuResult.menuPopupFound;
  debug.menuItemFound = menuResult.menuItemFound;
  debug.menuButtonDesc = menuResult.menuButtonDesc;
  debug.menuItemLabels = menuResult.menuItemLabels;
  if (!menuResult.opened) return { ok: false, debug };
  const ready = await waitForTranscriptPanel(3500);
  debug.openedAfterMenu = ready;
  return { ok: ready, debug };
}

function isTranscriptPanelOpen() {
  const panel =
    document.querySelector(
      'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-searchable-transcript"]'
    ) ||
    document.querySelector(
      'ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-transcript"]'
    ) ||
    document.querySelector(
      'ytd-engagement-panel-section-list-renderer[target-id*="transcript"]'
    ) ||
    document.querySelector("ytd-transcript-renderer") ||
    document.querySelector("ytd-transcript-body-renderer");
  if (!panel) return false;
  if (panel.hasAttribute("hidden")) return false;
  const visibility = panel.getAttribute("visibility");
  if (visibility && visibility.toLowerCase().includes("hidden")) return false;
  if (!isElementVisible(panel)) return false;
  return true;
}

async function openTranscriptPanelFromDirectButton() {
  const button = findTranscriptButton();
  debugLog("direct transcript button", button ? "found" : "missing");
  if (!button) return false;
  button.click();
  return true;
}

async function openTranscriptPanelFromMenu() {
  const buttons = findOverflowMenuButtons();
  debugLog("overflow menu buttons", buttons.length);
  if (buttons.length === 0) {
    return {
      opened: false,
      menuButtonFound: false,
      menuPopupFound: false,
      menuItemFound: false,
      menuButtonDesc: null,
      menuItemLabels: [],
    };
  }
  let lastMenuLabels = [];
  let lastButtonDesc = null;
  for (const button of buttons) {
    closeOpenMenus();
    button.scrollIntoView({ block: "center", inline: "center" });
    button.click();
    const menu = await waitForMenuPopup(1500);
    if (!menu) {
      debugLog("overflow menu did not open", describeElement(button));
      continue;
    }
    const menuItem = findTranscriptMenuItem(menu);
    if (menuItem) {
      debugLog("transcript menu item found");
      menuItem.click();
      return {
        opened: true,
        menuButtonFound: true,
        menuPopupFound: true,
        menuItemFound: true,
        menuButtonDesc: describeElement(button),
        menuItemLabels: [],
      };
    }
    const labels = collectMenuItemLabels(menu);
    lastMenuLabels = labels;
    lastButtonDesc = describeElement(button);
    debugLog("transcript menu item missing", {
      button: lastButtonDesc,
      menuItems: labels,
    });
    closeOpenMenus();
  }
  return {
    opened: false,
    menuButtonFound: true,
    menuPopupFound: true,
    menuItemFound: false,
    menuButtonDesc: lastButtonDesc,
    menuItemLabels: lastMenuLabels,
  };
}

function findOverflowMenuButtons() {
  const results = [];
  const addIfValid = (button) => {
    if (!button) return;
    if (!isElementVisible(button)) return;
    if (button.classList?.contains("ytp-subtitles-button")) return;
    if (button.closest("ytd-player")) return;
    results.push(button);
  };
  const scopedSelectors = [
    "#description ytd-menu-renderer button",
    "ytd-watch-metadata ytd-menu-renderer button",
    "#actions ytd-menu-renderer button",
  ];
  for (const selector of scopedSelectors) {
    const buttons = Array.from(document.querySelectorAll(selector));
    for (const button of buttons) addIfValid(button);
  }
  const generic = Array.from(
    document.querySelectorAll("ytd-menu-renderer button")
  );
  for (const button of generic) addIfValid(button);
  const labeled = results.filter((button) => {
    const label =
      (button.getAttribute("aria-label") ||
        button.getAttribute("title") ||
        button.getAttribute("data-tooltip-text") ||
        "").trim();
    const lower = label.toLowerCase();
    return (
      lower.includes("more") ||
      lower.includes("options") ||
      label.includes("更多") ||
      label.includes("操作") ||
      label.includes("menu")
    );
  });
  return dedupeButtons(labeled.length ? labeled : results);
}

function findTranscriptMenuItem(root) {
  const scope = root || document;
  const items = Array.from(
    scope.querySelectorAll(
      "ytd-menu-service-item-renderer, tp-yt-paper-item, ytd-menu-navigation-item-renderer"
    )
  );
  const keywords = [
    "transcript",
    "show transcript",
    "open transcript",
    "show full transcript",
    "字幕",
    "转录",
    "文字记录",
    "文字稿",
    "显示文字记录",
    "显示转录稿",
    "转录文本",
    "显示转录文本",
  ];
  for (const item of items) {
    const text =
      (item.getAttribute("aria-label") ||
        item.querySelector("#label, yt-formatted-string")?.textContent ||
        item.textContent ||
        "").trim();
    const lower = text.toLowerCase();
    if (
      keywords.some((keyword) => lower.includes(keyword) || text.includes(keyword))
    ) {
      if (!isElementVisible(item)) continue;
      return item;
    }
  }
  return null;
}

function findTranscriptButton() {
  const keywords = [
    "transcript",
    "show transcript",
    "字幕",
    "显示字幕",
    "转录",
    "显示转录",
    "文字记录",
    "文字稿",
    "显示文字记录",
    "显示转录稿",
  ];
  const scopes = [
    document.querySelector("ytd-video-description-transcript-section-renderer"),
    document.querySelector("ytd-watch-metadata"),
    document.querySelector("#description"),
  ].filter(Boolean);
  const selectors = [
    "button",
    "tp-yt-paper-button",
    "yt-button-shape button",
    "a",
  ];
  for (const scope of scopes) {
    for (const selector of selectors) {
      const buttons = Array.from(scope.querySelectorAll(selector));
      for (const button of buttons) {
        if (button.classList?.contains("ytp-subtitles-button")) continue;
        if (!isElementVisible(button)) continue;
        if (button.closest("ytd-menu-renderer")) continue;
        const label =
          (button.getAttribute("aria-label") ||
            button.getAttribute("title") ||
            button.getAttribute("data-tooltip-text") ||
            button.textContent ||
            "").trim();
        const lower = label.toLowerCase();
        if (
          keywords.some((keyword) => lower.includes(keyword) || label.includes(keyword))
        ) {
          return button;
        }
      }
    }
  }
  return null;
}

async function expandDescriptionIfNeeded() {
  const container = document.querySelector("ytd-watch-metadata");
  if (!container) return false;
  const expanded =
    container.querySelector("ytd-text-inline-expander[is-expanded]") ||
    container.querySelector('ytd-expander[expanded="true"]');
  if (expanded) return false;
  const selectors = [
    "button#expand",
    "tp-yt-paper-button#expand",
    "yt-button-shape button#expand",
    'button[aria-label*="Show more"]',
    'button[aria-label*="展开"]',
    'button[aria-label*="更多"]',
    'tp-yt-paper-button[aria-label*="Show more"]',
    'tp-yt-paper-button[aria-label*="展开"]',
    'tp-yt-paper-button[aria-label*="更多"]',
  ];
  for (const selector of selectors) {
    const button = container.querySelector(selector);
    if (!button) continue;
    if (!isElementVisible(button)) continue;
    const ariaExpanded = button.getAttribute("aria-expanded");
    if (ariaExpanded && ariaExpanded.toLowerCase() === "true") continue;
    debugLog("expanding description");
    button.click();
    await sleep(200);
    return true;
  }
  return false;
}

async function waitForTranscriptPanel(timeoutMs) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (isTranscriptPanelOpen()) return true;
    await sleep(200);
  }
  return false;
}

async function waitForMenuPopup(timeoutMs) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const dropdown =
      document.querySelector("tp-yt-iron-dropdown[opened]") ||
      document.querySelector("tp-yt-iron-dropdown[aria-hidden='false']");
    if (dropdown) {
      const menu =
        dropdown.querySelector("ytd-menu-popup-renderer") ||
        dropdown.querySelector("tp-yt-paper-listbox") ||
        dropdown;
      if (menu && isElementVisible(menu)) return menu;
    }
    const popup =
      document.querySelector("ytd-popup-container ytd-menu-popup-renderer") ||
      document.querySelector("ytd-menu-popup-renderer") ||
      document.querySelector("tp-yt-paper-listbox");
    if (popup && isElementVisible(popup)) return popup;
    await sleep(100);
  }
  return null;
}

async function readTranscriptFromDom() {
  const deadline = Date.now() + 3000;
  while (Date.now() < deadline) {
    const lines = readTranscriptLines();
    if (lines.length > 0) {
      return normalizeTranscriptLines(lines);
    }
    await sleep(200);
  }
  return "";
}

function readTranscriptLines() {
  const segments = Array.from(
    document.querySelectorAll("ytd-transcript-segment-renderer")
  );
  if (segments.length === 0) {
    return Array.from(
      document.querySelectorAll(
        "#segments-container #segment-text, ytd-transcript-body-renderer #segment-text"
      )
    )
      .map((node) => (node.textContent || "").trim())
      .filter(Boolean);
  }
  return segments
    .map((segment) => {
      const textEl =
        segment.querySelector("#segment-text") ||
        segment.querySelector(".segment-text") ||
        segment.querySelector("yt-formatted-string");
      return (textEl?.textContent || "").trim();
    })
    .filter(Boolean);
}

function normalizeTranscriptLines(lines) {
  const output = [];
  for (const line of lines) {
    const normalized = String(line).replace(/\s+/g, " ").trim();
    if (!normalized) continue;
    if (output[output.length - 1] === normalized) continue;
    output.push(normalized);
  }
  return output.join(" ");
}

function closeOpenMenus() {
  document.body.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));
  document.body.dispatchEvent(new KeyboardEvent("keyup", { key: "Escape" }));
}

function describeElement(element) {
  if (!element) return null;
  const label =
    element.getAttribute("aria-label") ||
    element.getAttribute("title") ||
    element.getAttribute("data-tooltip-text") ||
    "";
  const text = (element.textContent || "").trim().slice(0, 80);
  return {
    tag: element.tagName.toLowerCase(),
    id: element.id || "",
    label,
    text,
  };
}

function collectMenuItemLabels(root) {
  const scope = root || document;
  const items = Array.from(
    scope.querySelectorAll(
      "ytd-menu-service-item-renderer, tp-yt-paper-item, ytd-menu-navigation-item-renderer"
    )
  );
  return items
    .map((item) => {
      const text =
        (item.getAttribute("aria-label") ||
          item.querySelector("#label, yt-formatted-string")?.textContent ||
          item.textContent ||
          "").trim();
      return text.replace(/\s+/g, " ");
    })
    .filter(Boolean)
    .slice(0, 12);
}

function dedupeButtons(buttons) {
  const seen = new Set();
  const output = [];
  for (const button of buttons) {
    const key = button.dataset?.targetId || button.id || button.outerHTML;
    if (seen.has(key)) continue;
    seen.add(key);
    output.push(button);
  }
  return output;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
